// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

struct Octave
{
	float frequency;
	float2 offset;
	float amplitude;
};

RWStructuredBuffer<Octave> Octaves;
float2 Offset;
float Scale;
float Size;
float2 ChunkPosition;
int OctaveCount;
float Resolution;


[numthreads(5,5,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
